SHELL = /bin/bash

.PHONY: sim_foreign-economic-trends-and-implications-for-the-us_1984-03_84_31.png
sim_foreign-economic-trends-and-implications-for-the-us_1984-03_84_31.png:
	pdftoppm sim_foreign-economic-trends-and-implications-for-the-us_1984-03_84_31.pdf sim_foreign-economic-trends-and-implications-for-the-us_1984-03_84_31.png -png
